default_platform(:ios)

before_each do  
  # Downloads dependencies
  cocoapods(
    clean_install: true,
    use_bundle_exec: true,
    try_repo_update_on_error: true
  )
end

lane :build do |options|

  # Build framework
  xcodebuild(
    scheme: 'ReactNativeMdSdkExample',
    destination: 'platform=iOS Simulator,name=iPhone 12',
    clean: true,
    build: true
  )

end