name: Build Demo Apps

on: pull_request
jobs:
  setup:
    name: Setup environment
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1
      - uses: ruby/setup-ruby@v1
      - run: ls
      - name: Install node modules
        run: |
          cd example
          yarn install
  build_ios:
    name: Build iOS demo app
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Fastlane build iOS
        run: | 
          cd example/ios
          bundle install
          bundle exec fastlane build