name: Build Demo Apps

on: pull_request
jobs:
  iOSBuild:
    name: Build Demo Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.3'
      - name: Bundler
        run: |
          bundle install
      - name: Move to 'Example' directory
        run: |
          cd example
      - name: Install node modules
        run: |
          yarn install
      - name: Install Pods
        run: |
          cd ios
          pod install
      - name: Run iOS demo app
        run: |
          yarn ios